<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$textdomain = prev($fileparts);

$this->formActionPrepare($form) ?>

<?php
if (!isset($title)) {
    $title = (isset($this->title))
        ? $this->title
        : ucfirst($action) . ' ' . ucfirst($controller);
}

$this->headTitle($title);
?>
<header class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h3><?php echo $this->escapeHtml($this->translate($title)) ?></h3>
    </div>
</header>
<?php $elements = $this->elementsFlatArray($form) ?>
<?= $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6">
            <?php foreach ($elements as $element) : ?>
                <?= $this->renderElement($element) ?>
            <?php endforeach ?>
        </div>
    </div>
<?= $this->form()->closeTag() ?>
