<?php
if (!isset($__VIEWFILE__)) {
    throw new \Exception('$__VIEWFILE__ variable must be set with __FILE__ constant from the view file, in order for the partial to work.');
}

$fileparts = explode('/', $__VIEWFILE__);
$action = substr(end($fileparts), 0, -6);
$controller = prev($fileparts); 
$textdomain = prev($fileparts);

$this->formActionPrepare($form) ?>

<?php
if (!isset($title)) {
    $title = (isset($this->title))
        ? $this->title
        : ucfirst($action) . ' ' . ucfirst($controller);
}
if (!isset($bsCols)) {
    $bsCols = array(
        'sm' => 12, 
        'md' => 12, 
        'lg' => 12, 
    );
}

$this->headTitle($title);
?>
<header class="row">
        <div class="col-sm-<?= $bsCols['sm'] ?> col-md-<?= $bsCols['md'] ?> col-lg-<?= $bsCols['lg'] ?>">
        <h3><?php echo $this->escapeHtml($this->translate($title)) ?></h3>
    </div>
</header>
<?php $elements = $this->elementsFlatArray($form) ?>
<?= $this->form()->openTag($form) ?>
    <div class="row">
        <div class="col-sm-<?= $bsCols['sm'] ?> col-md-<?= $bsCols['md'] ?> col-lg-<?= $bsCols['lg'] ?>">
            <?php foreach ($elements as $element) : ?>
                <?= $this->renderElement($element) ?>
            <?php endforeach ?>
        </div>
    </div>
<?= $this->form()->closeTag() ?>
